In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install --upgrade opencv--python

Note: you may need to restart the kernel to use updated packages.


In [3]:
import cv2

In [4]:
cv2.__version__

'4.10.0'

In [5]:
import numpy as np

In [6]:
np.__version__

'2.0.1'

In [7]:
pip install --upgrade numpy

In [8]:
img =cv2.imread("C:\\Users\\ADMIN\\Guru balan\\hi.jpg")

In [9]:
print(img)

[[[ 40  33  16]
  [ 39  32  15]
  [ 37  30  13]
  ...
  [105  63  40]
  [105  63  40]
  [105  63  40]]

 [[ 40  33  16]
  [ 39  32  15]
  [ 37  30  13]
  ...
  [105  63  40]
  [105  63  40]
  [105  63  40]]

 [[ 40  33  16]
  [ 39  32  15]
  [ 37  30  13]
  ...
  [105  63  40]
  [105  63  40]
  [105  63  40]]

 ...

 [[ 59  45  27]
  [ 59  45  27]
  [ 58  44  26]
  ...
  [ 30  22   5]
  [ 21  15   2]
  [ 18  14   3]]

 [[ 58  44  26]
  [ 58  44  26]
  [ 57  43  25]
  ...
  [ 31  24   7]
  [ 17  13   2]
  [ 15  13   3]]

 [[ 53  39  21]
  [ 53  39  21]
  [ 54  40  22]
  ...
  [ 41  37  19]
  [ 27  23  12]
  [ 22  20  10]]]


In [10]:
cv2.imshow("Omg",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
g = cv2.imread("C:\\Users\\ADMIN\\Guru balan\\hi.jpg",0)

In [12]:
g

array([[29, 28, 26, ..., 61, 61, 61],
       [29, 28, 26, ..., 61, 61, 61],
       [29, 28, 26, ..., 61, 61, 61],
       ...,
       [41, 41, 40, ..., 18, 12, 11],
       [40, 40, 39, ..., 20, 10, 10],
       [35, 35, 36, ..., 32, 20, 17]], dtype=uint8)

In [13]:
cv2.imshow("Omg",g)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
cv2.imwrite("hhhh.jpg",g)

True

In [15]:
#COlor Space change

In [16]:
colours_avl  =[i for i in dir(cv2) if i .startswith("COLOR_BGR")]

In [17]:
print(colours_avl)

['COLOR_BGR2BGR555', 'COLOR_BGR2BGR565', 'COLOR_BGR2BGRA', 'COLOR_BGR2GRAY', 'COLOR_BGR2HLS', 'COLOR_BGR2HLS_FULL', 'COLOR_BGR2HSV', 'COLOR_BGR2HSV_FULL', 'COLOR_BGR2LAB', 'COLOR_BGR2LUV', 'COLOR_BGR2Lab', 'COLOR_BGR2Luv', 'COLOR_BGR2RGB', 'COLOR_BGR2RGBA', 'COLOR_BGR2XYZ', 'COLOR_BGR2YCR_CB', 'COLOR_BGR2YCrCb', 'COLOR_BGR2YUV', 'COLOR_BGR2YUV_I420', 'COLOR_BGR2YUV_IYUV', 'COLOR_BGR2YUV_UYNV', 'COLOR_BGR2YUV_UYVY', 'COLOR_BGR2YUV_Y422', 'COLOR_BGR2YUV_YUNV', 'COLOR_BGR2YUV_YUY2', 'COLOR_BGR2YUV_YUYV', 'COLOR_BGR2YUV_YV12', 'COLOR_BGR2YUV_YVYU', 'COLOR_BGR5552BGR', 'COLOR_BGR5552BGRA', 'COLOR_BGR5552GRAY', 'COLOR_BGR5552RGB', 'COLOR_BGR5552RGBA', 'COLOR_BGR5652BGR', 'COLOR_BGR5652BGRA', 'COLOR_BGR5652GRAY', 'COLOR_BGR5652RGB', 'COLOR_BGR5652RGBA', 'COLOR_BGRA2BGR', 'COLOR_BGRA2BGR555', 'COLOR_BGRA2BGR565', 'COLOR_BGRA2GRAY', 'COLOR_BGRA2RGB', 'COLOR_BGRA2RGBA', 'COLOR_BGRA2YUV_I420', 'COLOR_BGRA2YUV_IYUV', 'COLOR_BGRA2YUV_UYNV', 'COLOR_BGRA2YUV_UYVY', 'COLOR_BGRA2YUV_Y422', 'COLOR_BGRA2

In [18]:
print(len(colours_avl))

54


In [19]:
img1 = cv2.imread('C:\\Users\\ADMIN\\Guru balan\\hi.jpg')

In [20]:
img1

array([[[ 40,  33,  16],
        [ 39,  32,  15],
        [ 37,  30,  13],
        ...,
        [105,  63,  40],
        [105,  63,  40],
        [105,  63,  40]],

       [[ 40,  33,  16],
        [ 39,  32,  15],
        [ 37,  30,  13],
        ...,
        [105,  63,  40],
        [105,  63,  40],
        [105,  63,  40]],

       [[ 40,  33,  16],
        [ 39,  32,  15],
        [ 37,  30,  13],
        ...,
        [105,  63,  40],
        [105,  63,  40],
        [105,  63,  40]],

       ...,

       [[ 59,  45,  27],
        [ 59,  45,  27],
        [ 58,  44,  26],
        ...,
        [ 30,  22,   5],
        [ 21,  15,   2],
        [ 18,  14,   3]],

       [[ 58,  44,  26],
        [ 58,  44,  26],
        [ 57,  43,  25],
        ...,
        [ 31,  24,   7],
        [ 17,  13,   2],
        [ 15,  13,   3]],

       [[ 53,  39,  21],
        [ 53,  39,  21],
        [ 54,  40,  22],
        ...,
        [ 41,  37,  19],
        [ 27,  23,  12],
        [ 22,  20,  10]]

In [21]:
gray = cv2.cvtColor(img1,cv2.COLOR_BGR2GRAY)
hsv = cv2.cvtColor(img1,cv2.COLOR_BGR2HSV)
rgb = cv2.cvtColor(img1,cv2.COLOR_BGR2RGB)


In [22]:
cv2.imshow("gray",gray)
cv2.imshow("hsv",hsv)
cv2.imshow("RGB",rgb)
cv2.waitKey(0)
cv2.destroyAllWindows()