# importing libraries

In [1]:
import numpy as np
import cv2

# reading an image

In [2]:
img = cv2.imread("C:\\Users\\ADMIN\\faizal final sem\\hi.jpg")

In [3]:
shp = img.shape

In [4]:
shp

(894, 894, 3)

In [5]:
size = img.size

In [6]:
size

2397708

# img reshape

In [7]:
reshape_image = cv2.resize(img,(500,500))

In [8]:
reshape_image.size

750000

In [9]:
reshape_image.shape

(500, 500, 3)

In [10]:
cv2.imshow("Image", img)
cv2.imshow("Resize Image",reshape_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

# value of pixel

In [11]:
px = img[201,200]

In [12]:
print(px)

[203 159  88]


In [13]:
img

array([[[ 40,  33,  16],
        [ 39,  32,  15],
        [ 37,  30,  13],
        ...,
        [105,  63,  40],
        [105,  63,  40],
        [105,  63,  40]],

       [[ 40,  33,  16],
        [ 39,  32,  15],
        [ 37,  30,  13],
        ...,
        [105,  63,  40],
        [105,  63,  40],
        [105,  63,  40]],

       [[ 40,  33,  16],
        [ 39,  32,  15],
        [ 37,  30,  13],
        ...,
        [105,  63,  40],
        [105,  63,  40],
        [105,  63,  40]],

       ...,

       [[ 59,  45,  27],
        [ 59,  45,  27],
        [ 58,  44,  26],
        ...,
        [ 30,  22,   5],
        [ 21,  15,   2],
        [ 18,  14,   3]],

       [[ 58,  44,  26],
        [ 58,  44,  26],
        [ 57,  43,  25],
        ...,
        [ 31,  24,   7],
        [ 17,  13,   2],
        [ 15,  13,   3]],

       [[ 53,  39,  21],
        [ 53,  39,  21],
        [ 54,  40,  22],
        ...,
        [ 41,  37,  19],
        [ 27,  23,  12],
        [ 22,  20,  10]]

# ROI

In [14]:
#Select ROI
r = cv2.selectROI("select the area",img)

#crop img
cropped_image = img[int(r[1]):int(r[1]+r[3]),
                       int(r[0]):int(r[0]+r[2])]
cv2.imshow("Cropped Image",cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
cropped_image

array([[[212, 164,  92],
        [212, 165,  91],
        [213, 166,  92],
        ...,
        [123,  84,  39],
        [127,  87,  45],
        [130,  90,  55]],

       [[213, 165,  93],
        [213, 166,  92],
        [214, 167,  93],
        ...,
        [126,  87,  42],
        [124,  84,  42],
        [129,  89,  54]],

       [[214, 166,  94],
        [214, 167,  93],
        [214, 168,  91],
        ...,
        [129,  90,  45],
        [119,  81,  39],
        [125,  86,  48]],

       ...,

       [[ 91,  70,  49],
        [ 93,  72,  50],
        [102,  81,  59],
        ...,
        [ 73,  54,  39],
        [ 79,  60,  45],
        [ 84,  67,  54]],

       [[ 94,  73,  51],
        [ 96,  75,  53],
        [106,  85,  63],
        ...,
        [ 81,  63,  46],
        [ 81,  63,  46],
        [ 81,  62,  47]],

       [[ 97,  76,  54],
        [102,  79,  57],
        [115,  93,  68],
        ...,
        [ 83,  63,  46],
        [ 75,  55,  37],
        [ 70,  50,  33]]

# Save Cropped Image

In [16]:
cv2.imwrite('saveimage33.png',cropped_image)

True

In [17]:
img = cv2.imread("C:\\Users\\ADMIN\\Guru balan\\ai.jpeg")

In [ ]:
b,g,r = cv2.split(img)

# to display the split image
cv2.imshow('image',img)
cv2.imshow("blue",b)
cv2.imshow("green",g)
cv2.imshow("red",r)
cv2.waitKey(0)
cv2.destroyAllWindows