In [1]:
import cv2
import numpy as np

In [2]:
num = np.zeros((2,3))

In [3]:
num

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
image = np.zeros((512,512,3),np.uint8)
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
image

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [6]:
start_point = (10,10)
end_point = (511,511)
color = (225,165,220)
thickness = 10
cv2.line(image,start_point,end_point,color,thickness)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [225, 165, 220],
        [225, 165, 220],
        [225, 165, 220]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [225, 165, 220],
        [225, 165, 220],
        [225, 165, 220]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [225, 165, 220],
        [225, 165, 220],
        [225, 165, 220]]

In [7]:
cv2.imshow('image',image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
top_left_vertex = (384,0)
bottom_right_vertex = (510,128)
color = (0,225,128)
thickness = 5
cv2.rectangle(image, top_left_vertex,bottom_right_vertex,color,thickness)

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 225, 128],
        [  0, 225, 128],
        [  0, 225, 128]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 225, 128],
        [  0, 225, 128],
        [  0, 225, 128]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0, 225, 128],
        [  0, 225, 128],
        [  0, 225, 128]],

       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [225, 165, 220],
        [225, 165, 220],
        [225, 165, 220]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [225, 165, 220],
        [225, 165, 220],
        [225, 165, 220]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [225, 165, 220],
        [225, 165, 220],
        [225, 165, 220]]